/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as AuthenticatedLayoutIndexRouteImport } from './routes/_authenticated/_layout/index'
import { Route as AuthenticatedLayoutRecordsUploadDocumentRouteImport } from './routes/_authenticated/_layout/records/upload-document'
import { Route as AuthenticatedLayoutDocumentsDocumentManagementRouteImport } from './routes/_authenticated/_layout/documents/document-management'
import { Route as AuthenticatedLayoutDocumentsDocumentIdRouteImport } from './routes/_authenticated/_layout/documents/$documentId'
import { Route as AuthenticatedLayoutAdminUserManagementRouteImport } from './routes/_authenticated/_layout/admin/user-management'
import { Route as AuthenticatedLayoutAdminRegisterUserRouteImport } from './routes/_authenticated/_layout/admin/register-user'
import { Route as AuthenticatedLayoutAdminUsersUserIdUpdateRouteImport } from './routes/_authenticated/_layout/admin/users/$userId/update'

const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_authenticated/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutIndexRoute =
  AuthenticatedLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutRecordsUploadDocumentRoute =
  AuthenticatedLayoutRecordsUploadDocumentRouteImport.update({
    id: '/records/upload-document',
    path: '/records/upload-document',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutDocumentsDocumentManagementRoute =
  AuthenticatedLayoutDocumentsDocumentManagementRouteImport.update({
    id: '/documents/document-management',
    path: '/documents/document-management',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutDocumentsDocumentIdRoute =
  AuthenticatedLayoutDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutAdminUserManagementRoute =
  AuthenticatedLayoutAdminUserManagementRouteImport.update({
    id: '/admin/user-management',
    path: '/admin/user-management',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutAdminRegisterUserRoute =
  AuthenticatedLayoutAdminRegisterUserRouteImport.update({
    id: '/admin/register-user',
    path: '/admin/register-user',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutAdminUsersUserIdUpdateRoute =
  AuthenticatedLayoutAdminUsersUserIdUpdateRouteImport.update({
    id: '/admin/users/$userId/update',
    path: '/admin/users/$userId/update',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthenticatedLayoutIndexRoute
  '/admin/register-user': typeof AuthenticatedLayoutAdminRegisterUserRoute
  '/admin/user-management': typeof AuthenticatedLayoutAdminUserManagementRoute
  '/documents/$documentId': typeof AuthenticatedLayoutDocumentsDocumentIdRoute
  '/documents/document-management': typeof AuthenticatedLayoutDocumentsDocumentManagementRoute
  '/records/upload-document': typeof AuthenticatedLayoutRecordsUploadDocumentRoute
  '/admin/users/$userId/update': typeof AuthenticatedLayoutAdminUsersUserIdUpdateRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/': typeof AuthenticatedLayoutIndexRoute
  '/admin/register-user': typeof AuthenticatedLayoutAdminRegisterUserRoute
  '/admin/user-management': typeof AuthenticatedLayoutAdminUserManagementRoute
  '/documents/$documentId': typeof AuthenticatedLayoutDocumentsDocumentIdRoute
  '/documents/document-management': typeof AuthenticatedLayoutDocumentsDocumentManagementRoute
  '/records/upload-document': typeof AuthenticatedLayoutRecordsUploadDocumentRoute
  '/admin/users/$userId/update': typeof AuthenticatedLayoutAdminUsersUserIdUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/_layout/': typeof AuthenticatedLayoutIndexRoute
  '/_authenticated/_layout/admin/register-user': typeof AuthenticatedLayoutAdminRegisterUserRoute
  '/_authenticated/_layout/admin/user-management': typeof AuthenticatedLayoutAdminUserManagementRoute
  '/_authenticated/_layout/documents/$documentId': typeof AuthenticatedLayoutDocumentsDocumentIdRoute
  '/_authenticated/_layout/documents/document-management': typeof AuthenticatedLayoutDocumentsDocumentManagementRoute
  '/_authenticated/_layout/records/upload-document': typeof AuthenticatedLayoutRecordsUploadDocumentRoute
  '/_authenticated/_layout/admin/users/$userId/update': typeof AuthenticatedLayoutAdminUsersUserIdUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/login'
    | '/'
    | '/admin/register-user'
    | '/admin/user-management'
    | '/documents/$documentId'
    | '/documents/document-management'
    | '/records/upload-document'
    | '/admin/users/$userId/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/'
    | '/admin/register-user'
    | '/admin/user-management'
    | '/documents/$documentId'
    | '/documents/document-management'
    | '/records/upload-document'
    | '/admin/users/$userId/update'
  id:
    | '__root__'
    | '/_authenticated/_layout'
    | '/auth/login'
    | '/_authenticated/_layout/'
    | '/_authenticated/_layout/admin/register-user'
    | '/_authenticated/_layout/admin/user-management'
    | '/_authenticated/_layout/documents/$documentId'
    | '/_authenticated/_layout/documents/document-management'
    | '/_authenticated/_layout/records/upload-document'
    | '/_authenticated/_layout/admin/users/$userId/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout/': {
      id: '/_authenticated/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/records/upload-document': {
      id: '/_authenticated/_layout/records/upload-document'
      path: '/records/upload-document'
      fullPath: '/records/upload-document'
      preLoaderRoute: typeof AuthenticatedLayoutRecordsUploadDocumentRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/documents/document-management': {
      id: '/_authenticated/_layout/documents/document-management'
      path: '/documents/document-management'
      fullPath: '/documents/document-management'
      preLoaderRoute: typeof AuthenticatedLayoutDocumentsDocumentManagementRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/documents/$documentId': {
      id: '/_authenticated/_layout/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof AuthenticatedLayoutDocumentsDocumentIdRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/admin/user-management': {
      id: '/_authenticated/_layout/admin/user-management'
      path: '/admin/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AuthenticatedLayoutAdminUserManagementRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/admin/register-user': {
      id: '/_authenticated/_layout/admin/register-user'
      path: '/admin/register-user'
      fullPath: '/admin/register-user'
      preLoaderRoute: typeof AuthenticatedLayoutAdminRegisterUserRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/admin/users/$userId/update': {
      id: '/_authenticated/_layout/admin/users/$userId/update'
      path: '/admin/users/$userId/update'
      fullPath: '/admin/users/$userId/update'
      preLoaderRoute: typeof AuthenticatedLayoutAdminUsersUserIdUpdateRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutIndexRoute: typeof AuthenticatedLayoutIndexRoute
  AuthenticatedLayoutAdminRegisterUserRoute: typeof AuthenticatedLayoutAdminRegisterUserRoute
  AuthenticatedLayoutAdminUserManagementRoute: typeof AuthenticatedLayoutAdminUserManagementRoute
  AuthenticatedLayoutDocumentsDocumentIdRoute: typeof AuthenticatedLayoutDocumentsDocumentIdRoute
  AuthenticatedLayoutDocumentsDocumentManagementRoute: typeof AuthenticatedLayoutDocumentsDocumentManagementRoute
  AuthenticatedLayoutRecordsUploadDocumentRoute: typeof AuthenticatedLayoutRecordsUploadDocumentRoute
  AuthenticatedLayoutAdminUsersUserIdUpdateRoute: typeof AuthenticatedLayoutAdminUsersUserIdUpdateRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutIndexRoute: AuthenticatedLayoutIndexRoute,
  AuthenticatedLayoutAdminRegisterUserRoute:
    AuthenticatedLayoutAdminRegisterUserRoute,
  AuthenticatedLayoutAdminUserManagementRoute:
    AuthenticatedLayoutAdminUserManagementRoute,
  AuthenticatedLayoutDocumentsDocumentIdRoute:
    AuthenticatedLayoutDocumentsDocumentIdRoute,
  AuthenticatedLayoutDocumentsDocumentManagementRoute:
    AuthenticatedLayoutDocumentsDocumentManagementRoute,
  AuthenticatedLayoutRecordsUploadDocumentRoute:
    AuthenticatedLayoutRecordsUploadDocumentRoute,
  AuthenticatedLayoutAdminUsersUserIdUpdateRoute:
    AuthenticatedLayoutAdminUsersUserIdUpdateRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
